<?php
/**
 * @file
 * Code for the AE Participants feature.
 */

include_once 'ae_participants.features.inc';

/**
 * Implements hook_module_implements_alter().
 *
 * This hook is implemented to move our ae_participants_modules_enabled()
 * hook implementation to the bottom of the ordering so as to run after the
 * problematic features_modules_enabled() implementation.
 */
function ae_participants_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'modules_enabled') {
    $group = $implementations['ae_participants'];
    unset($implementations['ae_participants']);
    $implementations['ae_participants'] = $group;
  }
}

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for ae_participants's
 * profiles. This has to be done in this hook to run after both features
 * and defaultconfig which power the functionality. Hopefully a more general solution
 * can be found. More information - http://drupal.org/node/1837312.
 */
function ae_participants_modules_enabled($modules) {
  // Only run this logic if we are executing as part of an install profile
  if (variable_get('install_task', 'done') != 'done') {

    // Rebuild some caches so this all works right
    features_flush_caches();
    drupal_static_reset();

    // Load the defaultconfig permissions.
    include_once 'ae_participants.features.defaultconfig.inc';
    $roles = array();

    foreach (ae_participants_defaultconfig_user_default_permissions() as $permission => $config) {
      foreach ($config['roles'] as $role) {
        // Load if role has not been loaded before.
        if (empty($roles[$role])) {
          $roles[$role] = user_role_load_by_name($role);
        }
        // Grant the permissions.
        user_role_grant_permissions($roles[$role]->rid, array($permission));
      }
    }
  }
}
